version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ../:/var/www/
      - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '${FORWARD_APP_PORT:-80}:80'
    depends_on:
      - php
    container_name: 'media-expert-nginx'

  php:
    build:
      context: .
      dockerfile: dockerfiles/php
    volumes:
      - ../:/var/www/
      - ./.composer/:/.composer/
    container_name: 'media-expert-php'
